name: "Update packages"

on:
  schedule:
    # 5:32 every day
    - cron: "32 5 * * *"

  workflow_dispatch:

jobs:
  excavate:
    name: "Update packages"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Install Nix"
        uses: "cachix/install-nix-action@9280e7aca88deada44c930f1e2c78e21c3ae3edd" # v31.7.0
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: "nixpkgs=channel:nixos-unstable"

      - name: "Checkout"
        uses: "actions/checkout@v5"

      - name: "Convert to jj repo"
        run: |
          nix run nixpkgs#jujutsu -- git init --colocate
          nix run nixpkgs#jujutsu -- bookmark track main@origin

      - name: "Update"
        run: "./update/update.fish"
