name: "Update packages"

on:
  schedule:
    # 5:32 every day
    - cron: "32 5 * * *"

  workflow_dispatch:

jobs:
  excavate:
    name: "Update packages"
    runs-on: "ubuntu-latest"

    permissions:
      contents: write

    steps:
      - name: "Install Nix"
        uses: "cachix/install-nix-action@9280e7aca88deada44c930f1e2c78e21c3ae3edd" # v31.7.0
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: "nixpkgs=channel:nixos-unstable"

      - name: "Checkout"
        uses: "actions/checkout@v5"

      - name: "Setup Git"
        run: |
          git config --global user.name "nttis"
          git config --global user.email "42465069+nttis@users.noreply.github.com"

      - name: "Run update script"
        run: nix shell nixpkgs#nix-update nixpkgs#python3 --command python update/update.py

      - name: "Push changes"
        run: git push
